version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_dev

    environment:
      MONGO_INITDB_DATABASE: data
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
    ports:
      - "27019:27017"
    networks:
      - app_network
    volumes:
      - ./mongodb_data:/data/db

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: