
POST http://localhost:4570/userapi/user/login HTTP/1.1
content-type: application/json

# {
#     "userName": "chanyapatshell@hotmail.com",
#     "password": "0918208741asdasd"
# }

{
    "userName": "chanyapatshell9@gmail.com",
    "password": "12345678"
}