
@hostname = localhost
@port = 4570
@host = {{hostname}}:{{port}}
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImVmYjg2M2VlYyJ9.eyJhdWQiOiI0MGJjYmUwOC0yY2Y4LTQ1ZTItYTU5Zi1jNGM2NjEzZjRkZWYiLCJleHAiOjE3MDgxNTM0MTcsImlhdCI6MTcwODE0NjIxNywiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiI4MmQyZWZkMC0zNWEwLTRmYzItOGRlMy1lZDViNzU5YmJiMmQiLCJqdGkiOiJmMWVmZjM1Ny0wMzRlLTRhOTMtOWI3Yy1lMTMxM2Y3MGM2ZTMiLCJhdXRoZW50aWNhdGlvblR5cGUiOiJQQVNTV09SRCIsImVtYWlsIjoiY2hhbnlhcGF0X2FkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9tcnMxIiwiYXBwbGljYXRpb25JZCI6IjQwYmNiZTA4LTJjZjgtNDVlMi1hNTlmLWM0YzY2MTNmNGRlZiIsInJvbGVzIjpbImFkbWluIl0sInNpZCI6IjY5YzA0ZWE3LTg2YzQtNDE0OC1hOGI1LTVhZWU4MzBjOGEyZCIsImF1dGhfdGltZSI6MTcwODE0NjIxNywidGlkIjoiNWE3Mjc3ZmEtNjUzMC1iOTE3LWIzNTMtNGVjZGI5Yjg1ZmM5In0.cdU_B4ixQz0NfscQ0QyeMU4ZNjTRZimil_a95mR26yI
### login
POST http://{{host}}/userapi/user/login HTTP/1.1
content-type: {{contentType}}

{
    "userName": "chanyapat_admin@gmail.com",
    "password": "12345678"
}

# {
#     "userName": "chanyapatshell5@gmail.com",
#     "password": "12345678"
# }

# {
#     "userName": "chanyapatshell@gmail.com",
#     "password": "12345678"
# }


### refresh token
POST http://{{host}}/userapi/user/refresh/token HTTP/1.1
content-type: {{contentType}}

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImVmYjg2M2VlYyJ9.eyJhdWQiOiI0MGJjYmUwOC0yY2Y4LTQ1ZTItYTU5Zi1jNGM2NjEzZjRkZWYiLCJleHAiOjE3MDc3Mzc1MTEsImlhdCI6MTcwNzczMDMxMSwiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiJjNjllMDYyYy03YzMwLTRmZjQtYThiMy1iMDY3ZTc3MmI0NjYiLCJqdGkiOiJkYzM5NzhkZS05NjQ4LTQyNmEtYTE4OS00NmExNzkwZjgwZTkiLCJhdXRoZW50aWNhdGlvblR5cGUiOiJQQVNTV09SRCIsImVtYWlsIjoiY2hhbnlhcGF0c2hlbGxAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6Im1yczAwMSIsImFwcGxpY2F0aW9uSWQiOiI0MGJjYmUwOC0yY2Y4LTQ1ZTItYTU5Zi1jNGM2NjEzZjRkZWYiLCJyb2xlcyI6WyJjdXN0b21lciJdLCJzaWQiOiI3MjRlMTQ5ZC0xYTA1LTRjOWQtOTdmMC1kOGIzZDI0MjA5MTIiLCJhdXRoX3RpbWUiOjE3MDc3MzAzMTEsInRpZCI6IjVhNzI3N2ZhLTY1MzAtYjkxNy1iMzUzLTRlY2RiOWI4NWZjOSJ9.9qgX0lHCgr56cIpRkwV9eEJgRQvleR6U0yaJxj777vk",
  "refreshToken": "OUJuzL3_VXwKnDNbB6QfDhVJbJjUBydSEqDzArEz3DWlcXcipCNeEw"
}



### signup admin
POST http://{{host}}/userapi/user/admin/signup HTTP/1.1
token: {{token}}
content-type: {{contentType}}

{
    "userName": "admin_mrs1",
    "email" : "chanyapat_admin@gmail.com",
    "password": "12345678",
    "firstName" : "chanyapat",
	"lastName" : "rattamakot"
}

### signup
POST http://{{host}}/userapi/user/signup HTTP/1.1
content-type: {{contentType}}

{
    "userName": "shell01",
    "email" : "chanyapat1@gmail.com",
    "password": "12345678",
    "firstName" : "chanyapat1",
	"lastName" : "rattanakot1"
}

### edit
PUT http://{{host}}/userapi/user/03597719-333d-4e41-b22a-6432be2df115 HTTP/1.1
token: {{token}}
content-type: {{contentType}}

{
  "id": "Uc65bf471133a8be51280744dd",
  "uuid": "03597719-333d-4e41-b22a-6432be2df115",
  "username": "chanyapat9_username",
  "email": "chanyapatshell9_edit@gmail.com",
  "password": "$2a$14$Qys24Fngb4A6O8Bs8o1YQ.UfzWXuLVl42oCLH9Fbycvd8cXUsIeye",
  "firstName": "char9__edit",
  "lastName": "lchar9",
  "age": 10,
  "mobilePhone" : "0910910912",
  "created_at": "2024-02-04T08:13:05Z",
  "updated_at": "2024-02-04T08:13:05Z"
}

### patch
PATCH  http://{{host}}/userapi/user/03597719-333d-4e41-b22a-6432be2df115 HTTP/1.1
token: {{token}}
content-type: {{contentType}}

{
  "email": "chanyapatshell9_patch@gmail.com"
}



### get by uuid
GET http://{{host}}/userapi/user/03597719-333d-4e41-b22a-6432be2df115 HTTP/1.1
token: {{token}}
content-type: {{contentType}}


### get List
GET http://{{host}}/userapi/user?limit=&page=&search=&uuid=&sort=1&sortkey=email HTTP/1.1
token: {{token}}
content-type: {{contentType}}

### delete
DELETE  http://{{host}}/userapi/user/392b2529-5e34-42e3-9b8d-77f185e88b39 HTTP/1.1
token: {{token}}
content-type: {{contentType}}

### forgot/pass
POST  http://{{host}}/userapi/user/forgot/password HTTP/1.1
token:
content-type: {{contentType}}

{"email" : "chanyapatshell@gmail.com"}

### change/pass
PUT  http://{{host}}/userapi/user/change/password/c69e062c-7c30-4ff4-a8b3-b067e772b466 HTTP/1.1
token: {{token}}
content-type: {{contentType}}

{"password" : "12341234",
"newPassword" : "12345678"}
