
@hostname = localhost
@port = 4570
@host = {{hostname}}:{{port}}
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImVmYjg2M2VlYyJ9.eyJhdWQiOiI0MGJjYmUwOC0yY2Y4LTQ1ZTItYTU5Zi1jNGM2NjEzZjRkZWYiLCJleHAiOjE3MDg5NjEzNDUsImlhdCI6MTcwODk1NDIzNywiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiI4MmQyZWZkMC0zNWEwLTRmYzItOGRlMy1lZDViNzU5YmJiMmQiLCJqdGkiOiI3NTE1M2M2ZS1mY2FlLTQyMzEtODM0YS03NGRmNWYyNjc0NzMiLCJhdXRoZW50aWNhdGlvblR5cGUiOiJKV1RfU1NPIiwiZW1haWwiOiJjaGFueWFwYXRfYWRtaW5AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluX21yczEiLCJhcHBsaWNhdGlvbklkIjoiNDBiY2JlMDgtMmNmOC00NWUyLWE1OWYtYzRjNjYxM2Y0ZGVmIiwicm9sZXMiOlsiYWRtaW4iXSwiYXV0aF90aW1lIjoxNzA4OTU0MjM3LCJ0aWQiOiI1YTcyNzdmYS02NTMwLWI5MTctYjM1My00ZWNkYjliODVmYzkifQ.Jz0cNlzO78eawfCyiNBqyPCdwTR4prSP0tMwKkK2y40
### login
POST http://{{host}}/userapi/user/login HTTP/1.1
content-type: {{contentType}}

{
    "userName": "chanyapat_admin@gmail.com",
    "password": "12345678"
}

### refresh token
POST http://{{host}}/userapi/user/refresh/token HTTP/1.1
content-type: {{contentType}}

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImVmYjg2M2VlYyJ9.eyJhdWQiOiI0MGJjYmUwOC0yY2Y4LTQ1ZTItYTU5Zi1jNGM2NjEzZjRkZWYiLCJleHAiOjE3MDg5NjEzNDUsImlhdCI6MTcwODk1NDE0NSwiaXNzIjoiYWNtZS5jb20iLCJzdWIiOiI4MmQyZWZkMC0zNWEwLTRmYzItOGRlMy1lZDViNzU5YmJiMmQiLCJqdGkiOiJhMGU0YWRiNS03MDFiLTRlMjYtODIwMi02NDgyMGQ1YmRlYmIiLCJhdXRoZW50aWNhdGlvblR5cGUiOiJQQVNTV09SRCIsImVtYWlsIjoiY2hhbnlhcGF0X2FkbWluQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9tcnMxIiwiYXBwbGljYXRpb25JZCI6IjQwYmNiZTA4LTJjZjgtNDVlMi1hNTlmLWM0YzY2MTNmNGRlZiIsInJvbGVzIjpbImFkbWluIl0sInNpZCI6IjNiYTZlNmNhLTk5ZGUtNDlhOC1hNmE0LWM2N2JjZjZhY2FjZSIsImF1dGhfdGltZSI6MTcwODk1NDE0NSwidGlkIjoiNWE3Mjc3ZmEtNjUzMC1iOTE3LWIzNTMtNGVjZGI5Yjg1ZmM5In0.MAv1uy9ppYCKnNApxU4qe7dDWXaNvkywsBIQvM_-pjc",
  "refreshToken": "fwcWLY6LPiWLZBEMZeSmcFifrwiygHXtga7YlaLz-TipzChECmwlpA"
}

### logout
POST http://{{host}}/userapi/user/logout HTTP/1.1
content-type: {{contentType}}

{
  "refreshToken": "fwcWLY6LPiWLZBEMZeSmcFifrwiygHXtga7YlaLz-TipzChECmwlpAasdasda"
}



### signup admin
POST http://{{host}}/userapi/user/admin/signup HTTP/1.1
token: {{token}}
content-type: {{contentType}}

{
    "userName": "admin_mrs1",
    "email" : "chanyapat_admin@gmail.com",
    "password": "12345678",
    "firstName" : "chanyapat",
	"lastName" : "rattamakot"
}

### signup
POST http://{{host}}/userapi/user/signup HTTP/1.1
content-type: {{contentType}}

{
    "userName": "shell02",
    "email" : "chanyapat2@gmail.com",
    "password": "12345678",
    "firstName" : "chanyapat2",
	  "lastName" : "rattanakot2"
}

### edit
PUT http://{{host}}/userapi/user/03597719-333d-4e41-b22a-6432be2df115 HTTP/1.1
token: {{token}}
content-type: {{contentType}}

{
  "id": "Uc65bf471133a8be51280744dd",
  "uuid": "03597719-333d-4e41-b22a-6432be2df115",
  "username": "chanyapat9_username",
  "email": "chanyapatshell9_edit@gmail.com",
  "firstName": "char9__edit",
  "lastName": "lchar9",
  "age": 10,
  "mobilePhone" : "0910910912",
  "created_at": "2024-02-04T08:13:05Z",
  "updated_at": "2024-02-04T08:13:05Z"
}

### patch
PATCH  http://{{host}}/userapi/user/03597719-333d-4e41-b22a-6432be2df115 HTTP/1.1
token: {{token}}
content-type: {{contentType}}

{
  "email": "chanyapatshell9_patch@gmail.com"
}


### get by uuid
GET http://{{host}}/userapi/user/03597719-333d-4e41-b22a-6432be2df115 HTTP/1.1
token: {{token}}
content-type: {{contentType}}


### get List
GET http://{{host}}/userapi/user?limit=&page=&search=&uuid=&sort=1&sortkey=email HTTP/1.1
token: {{token}}
content-type: {{contentType}}

### delete
DELETE  http://{{host}}/userapi/user/392b2529-5e34-42e3-9b8d-77f185e88b39 HTTP/1.1
token: {{token}}
content-type: {{contentType}}

### forgot/pass
POST  http://{{host}}/userapi/user/forgot/password HTTP/1.1
token:
content-type: {{contentType}}

{"email" : "chanyapatshell@gmail.com"}

### change/pass
PUT  http://{{host}}/userapi/user/change/password/c69e062c-7c30-4ff4-a8b3-b067e772b466 HTTP/1.1
token: {{token}}
content-type: {{contentType}}

{"password" : "12341234",
"newPassword" : "12345678"}
